// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (user_uuid) VALUES ($1)
`

func (q *Queries) CreateAdmin(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, createAdmin, userUuid)
	return err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE user_uuid = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, userUuid)
	return err
}

const getAdminByUUID = `-- name: GetAdminByUUID :one
SELECT user_uuid FROM admins WHERE user_uuid = $1
`

func (q *Queries) GetAdminByUUID(ctx context.Context, userUuid uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAdminByUUID, userUuid)
	var user_uuid uuid.UUID
	err := row.Scan(&user_uuid)
	return user_uuid, err
}
