// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: franchise.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFranchise = `-- name: CreateFranchise :one
INSERT INTO franchises DEFAULT VALUES 
RETURNING uuid, created_at
`

func (q *Queries) CreateFranchise(ctx context.Context) (Franchise, error) {
	row := q.db.QueryRow(ctx, createFranchise)
	var i Franchise
	err := row.Scan(&i.Uuid, &i.CreatedAt)
	return i, err
}

const createVendeur = `-- name: CreateVendeur :one

INSERT INTO vendeurs (user_uuid, franchise_uuid) 
VALUES ($1, $2)
RETURNING user_uuid, franchise_uuid
`

type CreateVendeurParams struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
}

// -------------------------------------------
// VENDEURS (SALESPEOPLE)
func (q *Queries) CreateVendeur(ctx context.Context, arg CreateVendeurParams) (Vendeur, error) {
	row := q.db.QueryRow(ctx, createVendeur, arg.UserUuid, arg.FranchiseUuid)
	var i Vendeur
	err := row.Scan(&i.UserUuid, &i.FranchiseUuid)
	return i, err
}

const deleteFranchise = `-- name: DeleteFranchise :exec
DELETE FROM franchises 
WHERE uuid = $1
`

func (q *Queries) DeleteFranchise(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFranchise, argUuid)
	return err
}

const deleteVendeur = `-- name: DeleteVendeur :exec
DELETE FROM vendeurs 
WHERE user_uuid = $1
`

func (q *Queries) DeleteVendeur(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVendeur, userUuid)
	return err
}

const getFranchiseByUUID = `-- name: GetFranchiseByUUID :one
SELECT uuid, created_at FROM franchises 
WHERE uuid = $1
`

func (q *Queries) GetFranchiseByUUID(ctx context.Context, argUuid uuid.UUID) (Franchise, error) {
	row := q.db.QueryRow(ctx, getFranchiseByUUID, argUuid)
	var i Franchise
	err := row.Scan(&i.Uuid, &i.CreatedAt)
	return i, err
}

const getFranchisesByOwner = `-- name: GetFranchisesByOwner :many

SELECT f.uuid, f.created_at FROM franchises f
JOIN franchise_owners fo ON f.uuid = fo.franchise_uuid
WHERE fo.user_uuid = $1
`

// -------------------------------------------
// FRANCHISE OWNERS
func (q *Queries) GetFranchisesByOwner(ctx context.Context, userUuid uuid.UUID) ([]Franchise, error) {
	rows, err := q.db.Query(ctx, getFranchisesByOwner, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Franchise
	for rows.Next() {
		var i Franchise
		if err := rows.Scan(&i.Uuid, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnersByFranchise = `-- name: GetOwnersByFranchise :many
SELECT fo.user_uuid, u.email FROM franchise_owners fo
JOIN users u ON fo.user_uuid = u.uuid
WHERE fo.franchise_uuid = $1
`

type GetOwnersByFranchiseRow struct {
	UserUuid uuid.UUID `json:"user_uuid"`
	Email    string    `json:"email"`
}

func (q *Queries) GetOwnersByFranchise(ctx context.Context, franchiseUuid uuid.UUID) ([]GetOwnersByFranchiseRow, error) {
	rows, err := q.db.Query(ctx, getOwnersByFranchise, franchiseUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOwnersByFranchiseRow
	for rows.Next() {
		var i GetOwnersByFranchiseRow
		if err := rows.Scan(&i.UserUuid, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVendeurByUUID = `-- name: GetVendeurByUUID :one
SELECT user_uuid, franchise_uuid FROM vendeurs 
WHERE user_uuid = $1
`

func (q *Queries) GetVendeurByUUID(ctx context.Context, userUuid uuid.UUID) (Vendeur, error) {
	row := q.db.QueryRow(ctx, getVendeurByUUID, userUuid)
	var i Vendeur
	err := row.Scan(&i.UserUuid, &i.FranchiseUuid)
	return i, err
}

const listFranchises = `-- name: ListFranchises :many
SELECT uuid, created_at FROM franchises 
ORDER BY created_at DESC
`

func (q *Queries) ListFranchises(ctx context.Context) ([]Franchise, error) {
	rows, err := q.db.Query(ctx, listFranchises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Franchise
	for rows.Next() {
		var i Franchise
		if err := rows.Scan(&i.Uuid, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendeursByFranchise = `-- name: ListVendeursByFranchise :many
SELECT user_uuid, franchise_uuid FROM vendeurs 
WHERE franchise_uuid = $1
`

func (q *Queries) ListVendeursByFranchise(ctx context.Context, franchiseUuid uuid.UUID) ([]Vendeur, error) {
	rows, err := q.db.Query(ctx, listVendeursByFranchise, franchiseUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendeur
	for rows.Next() {
		var i Vendeur
		if err := rows.Scan(&i.UserUuid, &i.FranchiseUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFranchiseOwner = `-- name: RemoveFranchiseOwner :exec
DELETE FROM franchise_owners 
WHERE user_uuid = $1 AND franchise_uuid = $2
`

type RemoveFranchiseOwnerParams struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
}

func (q *Queries) RemoveFranchiseOwner(ctx context.Context, arg RemoveFranchiseOwnerParams) error {
	_, err := q.db.Exec(ctx, removeFranchiseOwner, arg.UserUuid, arg.FranchiseUuid)
	return err
}

const updateVendeurFranchise = `-- name: UpdateVendeurFranchise :one
UPDATE vendeurs 
SET franchise_uuid = $2 
WHERE user_uuid = $1
RETURNING user_uuid, franchise_uuid
`

type UpdateVendeurFranchiseParams struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
}

func (q *Queries) UpdateVendeurFranchise(ctx context.Context, arg UpdateVendeurFranchiseParams) (Vendeur, error) {
	row := q.db.QueryRow(ctx, updateVendeurFranchise, arg.UserUuid, arg.FranchiseUuid)
	var i Vendeur
	err := row.Scan(&i.UserUuid, &i.FranchiseUuid)
	return i, err
}
