// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: franchise_owners.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFranchiseOwner = `-- name: CreateFranchiseOwner :exec
INSERT INTO franchise_owners (user_uuid, franchise_uuid) VALUES ($1, $2)
`

type CreateFranchiseOwnerParams struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
}

func (q *Queries) CreateFranchiseOwner(ctx context.Context, arg CreateFranchiseOwnerParams) error {
	_, err := q.db.Exec(ctx, createFranchiseOwner, arg.UserUuid, arg.FranchiseUuid)
	return err
}

const deleteFranchiseOwner = `-- name: DeleteFranchiseOwner :exec
DELETE FROM franchise_owners WHERE user_uuid = $1 AND franchise_uuid = $2
`

type DeleteFranchiseOwnerParams struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
}

func (q *Queries) DeleteFranchiseOwner(ctx context.Context, arg DeleteFranchiseOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteFranchiseOwner, arg.UserUuid, arg.FranchiseUuid)
	return err
}

const getFranchiseOwnersByFranchise = `-- name: GetFranchiseOwnersByFranchise :many
SELECT user_uuid, franchise_uuid FROM franchise_owners WHERE franchise_uuid = $1
`

func (q *Queries) GetFranchiseOwnersByFranchise(ctx context.Context, franchiseUuid uuid.UUID) ([]FranchiseOwner, error) {
	rows, err := q.db.Query(ctx, getFranchiseOwnersByFranchise, franchiseUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FranchiseOwner
	for rows.Next() {
		var i FranchiseOwner
		if err := rows.Scan(&i.UserUuid, &i.FranchiseUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFranchiseOwnersByUser = `-- name: GetFranchiseOwnersByUser :many
SELECT user_uuid, franchise_uuid FROM franchise_owners WHERE user_uuid = $1
`

func (q *Queries) GetFranchiseOwnersByUser(ctx context.Context, userUuid uuid.UUID) ([]FranchiseOwner, error) {
	rows, err := q.db.Query(ctx, getFranchiseOwnersByUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FranchiseOwner
	for rows.Next() {
		var i FranchiseOwner
		if err := rows.Scan(&i.UserUuid, &i.FranchiseUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
