// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: produit.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFacture = `-- name: CreateFacture :one

INSERT INTO factures (uuid) 
VALUES (COALESCE($1, gen_random_uuid()))
RETURNING uuid
`

// -------------------------------------------
// FACTURES
func (q *Queries) CreateFacture(ctx context.Context, dollar_1 interface{}) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createFacture, dollar_1)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const createProduit = `-- name: CreateProduit :one
INSERT INTO produits (uuid) 
VALUES (COALESCE($1, gen_random_uuid()))
RETURNING uuid
`

func (q *Queries) CreateProduit(ctx context.Context, dollar_1 interface{}) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProduit, dollar_1)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const createVente = `-- name: CreateVente :one

INSERT INTO ventes (uuid, facture_uuid, vendeur_uuid, franchise_uuid, produit_uuid)
VALUES (COALESCE($1, gen_random_uuid()), $2, $3, $4, $5)
RETURNING uuid, facture_uuid, vendeur_uuid, franchise_uuid, produit_uuid
`

type CreateVenteParams struct {
	Column1       interface{} `json:"column_1"`
	FactureUuid   uuid.UUID   `json:"facture_uuid"`
	VendeurUuid   uuid.UUID   `json:"vendeur_uuid"`
	FranchiseUuid uuid.UUID   `json:"franchise_uuid"`
	ProduitUuid   uuid.UUID   `json:"produit_uuid"`
}

// -------------------------------------------
// VENTES
func (q *Queries) CreateVente(ctx context.Context, arg CreateVenteParams) (Vente, error) {
	row := q.db.QueryRow(ctx, createVente,
		arg.Column1,
		arg.FactureUuid,
		arg.VendeurUuid,
		arg.FranchiseUuid,
		arg.ProduitUuid,
	)
	var i Vente
	err := row.Scan(
		&i.Uuid,
		&i.FactureUuid,
		&i.VendeurUuid,
		&i.FranchiseUuid,
		&i.ProduitUuid,
	)
	return i, err
}

const deleteFacture = `-- name: DeleteFacture :exec
DELETE FROM factures 
WHERE uuid = $1
`

func (q *Queries) DeleteFacture(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFacture, argUuid)
	return err
}

const deleteProduit = `-- name: DeleteProduit :exec
DELETE FROM produits 
WHERE uuid = $1
`

func (q *Queries) DeleteProduit(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduit, argUuid)
	return err
}

const deleteVente = `-- name: DeleteVente :exec
DELETE FROM ventes 
WHERE uuid = $1
`

func (q *Queries) DeleteVente(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVente, argUuid)
	return err
}

const getFactureByUUID = `-- name: GetFactureByUUID :one
SELECT uuid FROM factures 
WHERE uuid = $1
`

func (q *Queries) GetFactureByUUID(ctx context.Context, argUuid uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFactureByUUID, argUuid)
	var uuid_2 uuid.UUID
	err := row.Scan(&uuid_2)
	return uuid_2, err
}

const getProduitByUUID = `-- name: GetProduitByUUID :one
SELECT uuid FROM produits 
WHERE uuid = $1
`

func (q *Queries) GetProduitByUUID(ctx context.Context, argUuid uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProduitByUUID, argUuid)
	var uuid_2 uuid.UUID
	err := row.Scan(&uuid_2)
	return uuid_2, err
}

const getVenteByUUID = `-- name: GetVenteByUUID :one
SELECT uuid, facture_uuid, vendeur_uuid, franchise_uuid, produit_uuid FROM ventes 
WHERE uuid = $1
`

func (q *Queries) GetVenteByUUID(ctx context.Context, argUuid uuid.UUID) (Vente, error) {
	row := q.db.QueryRow(ctx, getVenteByUUID, argUuid)
	var i Vente
	err := row.Scan(
		&i.Uuid,
		&i.FactureUuid,
		&i.VendeurUuid,
		&i.FranchiseUuid,
		&i.ProduitUuid,
	)
	return i, err
}

const getVenteDetailsWithVendeurEmail = `-- name: GetVenteDetailsWithVendeurEmail :one
SELECT 
    v.uuid AS vente_uuid,
    v.facture_uuid,
    v.vendeur_uuid,
    u.email AS vendeur_email,
    v.franchise_uuid,
    v.produit_uuid
FROM ventes v
JOIN users u ON v.vendeur_uuid = u.uuid
WHERE v.uuid = $1
`

type GetVenteDetailsWithVendeurEmailRow struct {
	VenteUuid     uuid.UUID `json:"vente_uuid"`
	FactureUuid   uuid.UUID `json:"facture_uuid"`
	VendeurUuid   uuid.UUID `json:"vendeur_uuid"`
	VendeurEmail  string    `json:"vendeur_email"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
	ProduitUuid   uuid.UUID `json:"produit_uuid"`
}

func (q *Queries) GetVenteDetailsWithVendeurEmail(ctx context.Context, argUuid uuid.UUID) (GetVenteDetailsWithVendeurEmailRow, error) {
	row := q.db.QueryRow(ctx, getVenteDetailsWithVendeurEmail, argUuid)
	var i GetVenteDetailsWithVendeurEmailRow
	err := row.Scan(
		&i.VenteUuid,
		&i.FactureUuid,
		&i.VendeurUuid,
		&i.VendeurEmail,
		&i.FranchiseUuid,
		&i.ProduitUuid,
	)
	return i, err
}

const listProduits = `-- name: ListProduits :many
SELECT uuid FROM produits
`

func (q *Queries) ListProduits(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProduits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentesByFacture = `-- name: ListVentesByFacture :many
SELECT uuid, facture_uuid, vendeur_uuid, franchise_uuid, produit_uuid FROM ventes 
WHERE facture_uuid = $1
`

func (q *Queries) ListVentesByFacture(ctx context.Context, factureUuid uuid.UUID) ([]Vente, error) {
	rows, err := q.db.Query(ctx, listVentesByFacture, factureUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vente
	for rows.Next() {
		var i Vente
		if err := rows.Scan(
			&i.Uuid,
			&i.FactureUuid,
			&i.VendeurUuid,
			&i.FranchiseUuid,
			&i.ProduitUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentesByFranchise = `-- name: ListVentesByFranchise :many
SELECT uuid, facture_uuid, vendeur_uuid, franchise_uuid, produit_uuid FROM ventes 
WHERE franchise_uuid = $1
`

func (q *Queries) ListVentesByFranchise(ctx context.Context, franchiseUuid uuid.UUID) ([]Vente, error) {
	rows, err := q.db.Query(ctx, listVentesByFranchise, franchiseUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vente
	for rows.Next() {
		var i Vente
		if err := rows.Scan(
			&i.Uuid,
			&i.FactureUuid,
			&i.VendeurUuid,
			&i.FranchiseUuid,
			&i.ProduitUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentesByVendeur = `-- name: ListVentesByVendeur :many
SELECT uuid, facture_uuid, vendeur_uuid, franchise_uuid, produit_uuid FROM ventes 
WHERE vendeur_uuid = $1
`

func (q *Queries) ListVentesByVendeur(ctx context.Context, vendeurUuid uuid.UUID) ([]Vente, error) {
	rows, err := q.db.Query(ctx, listVentesByVendeur, vendeurUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vente
	for rows.Next() {
		var i Vente
		if err := rows.Scan(
			&i.Uuid,
			&i.FactureUuid,
			&i.VendeurUuid,
			&i.FranchiseUuid,
			&i.ProduitUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
