// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFranchiseRecentSales = `-- name: GetFranchiseRecentSales :many
SELECT 
    v.uuid AS vente_uuid,
    v.facture_uuid,
    u.email AS vendeur_email,
    p.name AS produit_name,
    p.price AS produit_price
FROM ventes v
JOIN users u ON v.vendeur_uuid = u.uuid
JOIN produits p ON v.produit_uuid = p.uuid
WHERE v.franchise_uuid = $1
ORDER BY v.uuid DESC
LIMIT $2
`

type GetFranchiseRecentSalesParams struct {
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
	Limit         int32     `json:"limit"`
}

type GetFranchiseRecentSalesRow struct {
	VenteUuid    uuid.UUID     `json:"vente_uuid"`
	FactureUuid  uuid.UUID     `json:"facture_uuid"`
	VendeurEmail string        `json:"vendeur_email"`
	ProduitName  string        `json:"produit_name"`
	ProduitPrice pgtype.Float8 `json:"produit_price"`
}

func (q *Queries) GetFranchiseRecentSales(ctx context.Context, arg GetFranchiseRecentSalesParams) ([]GetFranchiseRecentSalesRow, error) {
	rows, err := q.db.Query(ctx, getFranchiseRecentSales, arg.FranchiseUuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFranchiseRecentSalesRow
	for rows.Next() {
		var i GetFranchiseRecentSalesRow
		if err := rows.Scan(
			&i.VenteUuid,
			&i.FactureUuid,
			&i.VendeurEmail,
			&i.ProduitName,
			&i.ProduitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFranchiseSalesSummary = `-- name: GetFranchiseSalesSummary :one
SELECT 
    COALESCE(COUNT(v.uuid), 0)::bigint AS total_sales,
    COALESCE(SUM(p.price), 0.0)::float AS total_revenue
FROM ventes v
JOIN produits p ON v.produit_uuid = p.uuid
WHERE v.franchise_uuid = $1
`

type GetFranchiseSalesSummaryRow struct {
	TotalSales   int64   `json:"total_sales"`
	TotalRevenue float64 `json:"total_revenue"`
}

func (q *Queries) GetFranchiseSalesSummary(ctx context.Context, franchiseUuid uuid.UUID) (GetFranchiseSalesSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFranchiseSalesSummary, franchiseUuid)
	var i GetFranchiseSalesSummaryRow
	err := row.Scan(&i.TotalSales, &i.TotalRevenue)
	return i, err
}

const getFranchiseSellersCount = `-- name: GetFranchiseSellersCount :one
SELECT COUNT(*)::bigint FROM vendeurs 
WHERE franchise_uuid = $1
`

func (q *Queries) GetFranchiseSellersCount(ctx context.Context, franchiseUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFranchiseSellersCount, franchiseUuid)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getFranchiseTopProducts = `-- name: GetFranchiseTopProducts :many
SELECT 
    p.uuid,
    p.name,
    p.price,
    COUNT(v.uuid)::bigint AS sales_count,
    COALESCE(SUM(p.price), 0.0)::float AS revenue
FROM ventes v
JOIN produits p ON v.produit_uuid = p.uuid
WHERE v.franchise_uuid = $1
GROUP BY p.uuid, p.name, p.price
ORDER BY sales_count DESC, revenue DESC
LIMIT $2
`

type GetFranchiseTopProductsParams struct {
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
	Limit         int32     `json:"limit"`
}

type GetFranchiseTopProductsRow struct {
	Uuid       uuid.UUID     `json:"uuid"`
	Name       string        `json:"name"`
	Price      pgtype.Float8 `json:"price"`
	SalesCount int64         `json:"sales_count"`
	Revenue    float64       `json:"revenue"`
}

func (q *Queries) GetFranchiseTopProducts(ctx context.Context, arg GetFranchiseTopProductsParams) ([]GetFranchiseTopProductsRow, error) {
	rows, err := q.db.Query(ctx, getFranchiseTopProducts, arg.FranchiseUuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFranchiseTopProductsRow
	for rows.Next() {
		var i GetFranchiseTopProductsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Price,
			&i.SalesCount,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFranchiseTopSellers = `-- name: GetFranchiseTopSellers :many
SELECT 
    u.uuid,
    u.email,
    COUNT(v.uuid)::bigint AS sales_count,
    COALESCE(SUM(p.price), 0.0)::float AS revenue
FROM ventes v
JOIN vendeurs vend ON v.vendeur_uuid = vend.user_uuid
JOIN users u ON vend.user_uuid = u.uuid
JOIN produits p ON v.produit_uuid = p.uuid
WHERE v.franchise_uuid = $1
GROUP BY u.uuid, u.email
ORDER BY sales_count DESC, revenue DESC
`

type GetFranchiseTopSellersRow struct {
	Uuid       uuid.UUID `json:"uuid"`
	Email      string    `json:"email"`
	SalesCount int64     `json:"sales_count"`
	Revenue    float64   `json:"revenue"`
}

func (q *Queries) GetFranchiseTopSellers(ctx context.Context, franchiseUuid uuid.UUID) ([]GetFranchiseTopSellersRow, error) {
	rows, err := q.db.Query(ctx, getFranchiseTopSellers, franchiseUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFranchiseTopSellersRow
	for rows.Next() {
		var i GetFranchiseTopSellersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Email,
			&i.SalesCount,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
