// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAdminData = `-- name: GetAdminData :one
SELECT u.email, u.uuid, u.role FROM admins a
JOIN user_public_data u on u.UUID=a.user_uuid
WHERE a.user_uuid=$1
`

func (q *Queries) GetAdminData(ctx context.Context, userUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getAdminData, userUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const getFranchiseOwnerData = `-- name: GetFranchiseOwnerData :one
SELECT u.email, u.uuid, u.role FROM franchise_owners fo
JOIN user_public_data u ON u.uuid = fo.user_uuid
WHERE fo.user_uuid = $1
`

func (q *Queries) GetFranchiseOwnerData(ctx context.Context, userUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getFranchiseOwnerData, userUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, password_hash FROM users WHERE email=$1
`

type GetUserByEmailRow struct {
	Uuid         uuid.UUID `json:"uuid"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.Uuid, &i.PasswordHash)
	return i, err
}

const getUserDataByUUID = `-- name: GetUserDataByUUID :one
SELECT email, uuid, role FROM user_public_data WHERE uuid=$1
`

func (q *Queries) GetUserDataByUUID(ctx context.Context, argUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getUserDataByUUID, argUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const getVendeurData = `-- name: GetVendeurData :one
SELECT u.email, u.uuid, u.role FROM vendeurs v
JOIN user_public_data u ON u.uuid = v.user_uuid
WHERE v.user_uuid = $1
`

func (q *Queries) GetVendeurData(ctx context.Context, userUuid uuid.UUID) (UserPublicDatum, error) {
	row := q.db.QueryRow(ctx, getVendeurData, userUuid)
	var i UserPublicDatum
	err := row.Scan(&i.Email, &i.Uuid, &i.Role)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT email, uuid, role FROM user_public_data
`

func (q *Queries) ListUsers(ctx context.Context) ([]UserPublicDatum, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPublicDatum
	for rows.Next() {
		var i UserPublicDatum
		if err := rows.Scan(&i.Email, &i.Uuid, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUser = `-- name: NewUser :one
INSERT INTO users (email, password_hash, role) VALUES($1, $2, $3)
RETURNING uuid, email, password_hash, role
`

type NewUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         Role   `json:"role"`
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, newUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const newVendeur = `-- name: NewVendeur :exec
INSERT INTO vendeurs(user_uuid, franchise_uuid) VALUES($1, $2)
`

type NewVendeurParams struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	FranchiseUuid uuid.UUID `json:"franchise_uuid"`
}

func (q *Queries) NewVendeur(ctx context.Context, arg NewVendeurParams) error {
	_, err := q.db.Exec(ctx, newVendeur, arg.UserUuid, arg.FranchiseUuid)
	return err
}
